{% set version = "3.0.1" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: 63934563a7a7b7186335858206a0b9be6043163b8b54a26cd3b3299a9e5e391f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - entrypoints
    - jinja2
    - jsonschema
    - numpy
    - pandas
    - six
    - toolz
    - typing >=3.6  # [py<35]

test:
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
  commands:
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.examples
    - altair.expr
    - altair.sphinxext
    - altair.tests
    - altair.utils
    - altair.vega
    - altair.vega.v3
    - altair.vega.v3.schema
    - altair.vega.v4
    - altair.vega.v4.schema
    - altair.vega.v5
    - altair.vega.v5.schema
    - altair.vegalite
    - altair.vegalite.v2
    - altair.vegalite.v2.schema
    - altair.vegalite.v3
    - altair.vegalite.v3.schema

about:
  home: http://github.com/altair-viz/altair
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
