{% set name = "altair" %}
{% set version = "5.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altair-{{ version }}.tar.gz
  sha256: d960ebe6178c56de3855a68c47b516be38640b73fb3b5111c2a9ca90546dd73d

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
  run:
    - python
    - jinja2
    - jsonschema >=3.0
    - typing-extensions >=4.10.0
    - packaging
    - narwhals >=1.14.2
  run_constrained:
    - vl-convert-python >=1.7.0

test:
  imports:
    - altair
    - altair.expr
    - altair.utils
    - altair.vegalite
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets >=0.9.0
    - anywidget >=0.9.0
    - recommonmark
    - ipython
    - pip
  commands:
    - pip check
    - python -m pytest --pyargs --doctest-modules altair

about:
  home: https://altair-viz.github.io
  dev_url: https://github.com/altair-viz/altair
  doc_url: https://altair-viz.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A declarative statistical visualization library for Python
  description: A declarative statistical visualization library for Python

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
