{% set name = "altair" %}
{% set version = "5.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altair-{{ version }}.tar.gz
  sha256: 087d7033cb2d6c228493a053e12613058a5d47faf6a36aea3ff60305fd8b4cb0

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - python
    - pip
    - hatchling
    - wheel
  run:
    - python
    - importlib-metadata  # [py<38]
    - typing-extensions >=4.0.1  # [py<311]
    - jinja2
    - jsonschema >=3.0
    - numpy
    - pandas >=0.18
    - toolz

test:
  imports:
    - altair
    - altair.expr
    - altair.utils
    - altair.vegalite
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
    - pip
  commands:
    - pip check
    - python -m pytest --pyargs --doctest-modules altair

about:
  home: https://altair-viz.github.io
  dev_url: https://github.com/altair-viz/altair
  doc_url: https://altair-viz.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A declarative statistical visualization library for Python
  description: A declarative statistical visualization library for Python

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
