# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "1.2.1" %}

package:
    name: altair
    version: {{ version }}

source:
    fn: altair-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
    md5: be6f597785b99be09051c0ca2f4d4bd1

build:
    noarch: python
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pandas
        - vega 0.4.4
        - traitlets >=4.3.1

test:
    requires:
        - pytest
    imports:
        - altair
        - altair.datasets
        - altair.examples

about:
    home: http://github.com/altair-viz/altair
    license: BSD 3-clause
    summary: 'High-level declarative visualization library for Python.'

extra:
    recipe-maintainers:
        - ellisonbg
        - jakevdp
