{% set version = "2.0.0" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://github.com/altair-viz/altair/archive/v{{ version }}.tar.gz
  sha256: 52d4168fc8da270048a231ac0ddbc5a14063ee97c6676fc3e45eec3621429ed3

build:2
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - entrypoints
    - jsonschema
    - numpy
    - pandas
    - python
    - six
    - toolz
    - typing

test:
  source_files:
    - altair
  requires:
    - docutils
    - jinja2
    - pytest
    - sphinx
    - vega_datasets
  commands:
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.expr
    - altair.sphinxext
    - altair.utils
    - altair.vega
    - altair.vega.v2
    - altair.vega.v2.schema
    - altair.vega.v3
    - altair.vega.v3.schema
    - altair.vegalite
    - altair.vegalite.v1
    - altair.vegalite.v1.schema
    - altair.vegalite.v2
    - altair.vegalite.v2.examples
    - altair.vegalite.v2.schema

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python.'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
