{% set version = "4.1.0" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: 3edd30d4f4bb0a37278b72578e7e60bc72045a8e6704179e2f4738e35bc12931

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - entrypoints
    - jinja2
    - jsonschema
    - numpy >=0.18
    - pandas
    - toolz

test:
  source_files:
    - altair
  requires:
    - pytest
    - sphinx
    - docutils
    - vega_datasets
    - recommonmark
    - ipython
    - pip
  commands:
    - pip check
    - python -m pytest --pyargs --doctest-modules altair
  imports:
    - altair
    - altair.examples
    - altair.expr
    - altair.sphinxext
    - altair.tests
    - altair.utils
    - altair.vega
    - altair.vega.v5
    - altair.vega.v5.schema
    - altair.vegalite
    - altair.vegalite.v3
    - altair.vegalite.v3.schema
    - altair.vegalite.v4
    - altair.vegalite.v4.schema

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Altair: A declarative statistical visualization library for Python'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
