{% set name = "altair" %}
{% set version = "4.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altair-{{ version }}.tar.gz
  sha256: 39399a267c49b30d102c10411e67ab26374156a84b1aeb9fcd15140429ba49c5

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - importlib-metadata  # [py<38]
    - jinja2
    - jsonschema >=3.0
    - numpy
    - pandas >=0.18
    - toolz
    - typing-extensions >=4.0.1  # [py<311]

test:
  imports:
    - altair
    - altair.expr
    - altair.utils
    - altair.vegalite
  source_files:
    - altair
  requires:
    - pytest
    - vega_datasets
    - ipython
    - pip
  commands:
    - pip check
    - python -m pytest --pyargs --doctest-modules altair

about:
  home: https://altair-viz.github.io
  dev_url: https://github.com/altair-viz/altair
  doc_url: https://altair-viz.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A declarative statistical visualization library for Python
  description: A declarative statistical visualization library for Python

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
