{% set version = "1.2.1" %}

package:
  name: altair
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/altair/altair-{{ version }}.tar.gz
  sha256: c1303f77f1ba4d632f2958c83c0f457b2b969860b1ac9adfb872aefa1780baa7

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pandas
    - vega 0.4.4
    - traitlets >=4.3.1

test:
  requires:
    - pytest
  imports:
    - altair
    - altair.datasets
    - altair.examples

about:
  home: http://github.com/altair-viz/altair
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'High-level declarative visualization library for Python.'

extra:
  recipe-maintainers:
    - ellisonbg
    - jakevdp
