travis:
  secure:
    BINSTAR_TOKEN: V5PkLGM+Ufh6HokMuaLWjwoarp5Wo1DlGoB8asIuFU1W2HatJZcN/Syj5+9owOvtE3ySJ6RhaPZ/jkJ1ryV2Ab9uD4JCxWGzlGZLx2gm1nRVTF1Tj3KvtKwjzhXbcJuMVtXyte/PUipYHxQ8Uu5MlcKWzjQRUWwwhLYk97YOYMD+57Tyx6EuLDff6476gMKb9aC0u8WD6BijCT30l7MERT/cde4c7iWA/r0lFMBkSL5Fc39ComgpSYtFkVMjDEv+t/JzGyarQyzK6dxhsxaCPRwD2Tlnc03IqDYV9IqZ7fzj6wMTYPFXLM/1lz163oqZEf9Rqbz7FtIO6IFL801vtPdbGFwcQV4Rq+RVZsfo98d7cjN6v6C433QV8z03x1YnqLHRVbZePzHtRAQvZ4l1Zklipye8/rMU9gwpSNchK56SMzd8ju/Ge/+IdKfmMIPZnoeQtHZ7YVCq5XsCMfLeJwC2umoH+Li/X3wMSgiv8MVRE/7z1fYW/MAb9GMaA9p0xgmka8sgyqlHFW3JRPvCy71NJXAJNnRlRVulEdrMTFP8kiXJF+lDX4ei+Cbz4wsOoJLzIEQGY929Q2kOZx/BmS8lqfSJ7J2BUuFTxOF3TgNlRQ0dD1UXSm4aHRvlv2oH0AA6dqfMBV89iqrOiwE0lL6sb4ea5ObwNdSo/g8Pdf4=
appveyor:
  secure:
    BINSTAR_TOKEN: /XxwAsgp0EItmAhoPSov/h0BtAFNj2BuuEqnhgaP9l7Rw2yLBM1lD+3q4LvpVm3B
