travis:
  secure:
    BINSTAR_TOKEN: XRW1z1ywLZ581Uz7YKZF6JPiDMKbjoJDCmU3Wl1gf8gWjm0GYmoBtbqmEw0e0zJCuJ5rODDolnmoICUPbvMzf/PxvKhHaxScPYs5ZzUoSlHkXbAJq89FBirhTI5jey5H1mLJZ3TwCyjaIDNtgXNMps3ZOzujxGeaQ0jIn+Kj/bWU+YBi2zSs8ZxOuAP1FhOgXI61CBRnsTI8nZ5irVMg+vC8AO1mOfDxua+T05N9UQAFJtosOEzD2fr7wYaeUL/B/aEMBMCGJWvMTZtnhS5Z06udoUv1OzgPw+yZSSxG50e7rMyRxE7kxKPSlfer+RYvzFSEMLXaTQ22e0nKdYRzOlebYxtKj8tJcywd4zwM8K/YZXtsiOGcOFeQYHMl+qrCXKhm6zqejkVtLaKQ+6PMgPx5h5K+vkhdEsNxJopZ6QGjtel0kurzu/LhcFS9YYu7YcVsUQ+NRJxvS0fjHQlh0iX4HH0hBoVQSmEyRFad5hZonOgTsE74VDsM5ArxhiN+gPwNB5X2fvL4hkjKxJoM4/NkJxPef98Kbp9JzeYxR3mz0fRkthrvo3ZIAY/9+2dl6hsViJ3jGYHJiVKaBQTqW12X4EBH4OLu7oC8PwBRCaBumUpDDXO3L71NKq9S/KmiuZbBBnTgb/7ZFU4sRwlphsSqnyzkMXB+XifE20kK3M0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
