travis:
  secure:
    BINSTAR_TOKEN: OcFnPDxnB+I+yPK3yeOpDs7VKFHWE0LpdEr838Yvb0MiRiZXLjCuRU21YKZzvLNyjCltCpHbvIdNhb00gCo5ph2uSgKrRCe/dgsKeSISI06fhvGCeZfa0RtMn+rzY9FlvEivcRp/cd3/Kbe0luSh4ZwiMxcZy5khCY0HPy8Xl8oZ7XOOyATCXlJUd/tz9e1hwx6Ff4TWPpWqL37GRZ2EiU4FWH5GVBSZCwiZLnRr0RWxQ4eJeosyQySa+AAevo9LRWlIeyzVnrXW4bKMwHcYJQg56i419Rmoe1/Wwn2zLoc8k2ZwAfOuP8g7fVOxwQQQJdmGnYC3aCSZWBiPtgSXIK8opAVdPTPvA2yeczFYr514136Zgb3HtUFUVVrXtR7dKDO6fIGH+vh92NJH8hrVKHdRciNwlwDk0U5KkGn3LJw02D9dfpKd1vFMtAVTrD6K5AnfbUvK3WWt+JYdihz7lAQ2g7TSz9yHc24lKcXmi7k6CzxX/NpBVywKUtr4OQJ49COBGCo7yim9gwDzsiniEXFo6DtLLblblYSkiwQKc0vhIuIJkwE0r3lxDZ+TJ1yCapuCDKgbRHcbMBtfJuEtaUPKQBReCQYuUBdCPdBz+4ftT8xfOrhaSk9gfyHuwqsh9E3365odFjNKpiCpQyoYS3aoul0vKVfkBk4do/jkBQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
